In [4]:
import numpy as np
from sklearn import preprocessing 
#an array with 4 rows (vectors) and 3 columns (feature)
data = np.array([[1, 1, 2], [0, 2, 3], [1, 0, 1], [0, 1, 0]])
print(data)

#To encode categorical integer features as a one-hot numeric array
#The first row of code sets the encoder, then the fit() function fits the OneHotEncoder object to a data array. 
encoder = preprocessing.OneHotEncoder()
encoder.fit(data)

#Transform the data array using one-hot encoding.
encoded_vector = encoder.transform([[1, 2, 3]]).toarray()
print(encoded_vector)
#[[0. 1. 0. 0. 1. 0. 0. 0. 1.]]
#[[0, 1, 0, 1, 2, 0, 1, 2, 3, 4]]


[[1 1 2]
 [0 2 3]
 [1 0 1]
 [0 1 0]]
[[0. 1. 0. 0. 1. 0. 0. 0. 1.]]
