In [1]:
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 19 13:55:17 2020
Data Preprocessing
@author: kujus
"""
import numpy as np
from sklearn import preprocessing

#an array with 4 rows (vectors) and 3 columns (feature)
data = np.array([[1, 1, 2], [0, 2, 3], [1, 0, 1], [0, 1, 0]])
print(data)

label_encoder = preprocessing.LabelEncoder()

[[1 1 2]
 [0 2 3]
 [1 0 1]
 [0 1 0]]
